### ISSUE TITLE
Trojan:Win32/Sabsik.FL.A!ml

### ISSUE THREAD

**Issue by Wells83** [SYSOFTEK/SMM-Enshrouded#1]
Trojan:Win32/Sabsik.FL.A!ml detecté par windows defender, c'est balo

**Comment by SYSOFTEK** [comment]
Bonjour, c'est sur la version compilé?

**Comment by Wells83** [comment]
Oui c'est en lançant lexe compilé. Sur un Windows Serveur 2019

**Comment by SYSOFTEK** [comment]
Merci, je vais chercher quelle partie du code pose problème.

**Comment by SYSOFTEK** [comment]
Bonjour, j'ai trouvé d'où viens le problème, c'est le script python cpuramio.exe qui fait les détections de faux positif : 
lorsque je compile le script AutoIt .au3, sans inclure le fichier cpuramio.exe, il n'y a plus de détection sur Virus total.
Je vais essayer de trouver une solution.

**Comment by SYSOFTEK** [comment]
Bonjour, je viens de mettre le code à jour.
Il n'utilise plus de script python, et ne cause plus de faux positif.
Si vous avez un moment pour tester et me tenir au courant si le problème est résolus.
Merci.

**Comment by Wells83** [comment]
c'est ok !
